# Generated by Django 5.0.14 on 2026-07-27 22:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('online', 'Online'), ('away', 'Ausente'), ('busy', 'Ocupado'), ('offline', 'Offline')], default='offline', max_length=10, verbose_name='Status')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Última vez visto')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online')),
                ('current_session_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Sessão atual')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'db_table': 'presence',
                'indexes': [models.Index(fields=['status'], name='presence_status_4811fe_idx'), models.Index(fields=['is_online'], name='presence_is_onli_1aca8a_idx'), models.Index(fields=['last_seen_at'], name='presence_last_se_7d0b24_idx')],
            },
        ),
    ]
