# Generated by Django 5.0.14 on 2026-07-27 22:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('welcome_message', models.TextField(default='Olá! Bem-vindo(a)! Escolha um setor para atendimento:', verbose_name='Mensagem de boas-vindas')),
                ('menu_message', models.TextField(default='Digite o número do setor desejado:', verbose_name='Mensagem do menu')),
                ('fallback_message', models.TextField(default='Opção inválida. Por favor, escolha uma opção válida.', verbose_name='Mensagem de fallback')),
                ('business_hours_enabled', models.BooleanField(default=False, verbose_name='Horário comercial ativo')),
                ('business_hours', models.JSONField(blank=True, default=dict, verbose_name='Horários comerciais')),
                ('outside_hours_message', models.TextField(default='No momento estamos fora do horário de atendimento. Deixe sua mensagem que retornaremos em breve.', verbose_name='Mensagem fora do horário')),
                ('max_attempts', models.IntegerField(default=3, verbose_name='Tentativas máximas')),
                ('use_ai', models.BooleanField(default=False, verbose_name='Usar IA')),
                ('ai_prompt', models.TextField(blank=True, default='', verbose_name='Prompt da IA')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração do Bot',
                'verbose_name_plural': 'Configurações do Bot',
                'db_table': 'bot_config',
            },
        ),
        migrations.CreateModel(
            name='BotMenuOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('option_key', models.CharField(max_length=10, verbose_name='Tecla')),
                ('label', models.CharField(max_length=255, verbose_name='Rótulo')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('bot_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_options', to='bot.botconfig', verbose_name='Configuração do Bot')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='Empresa')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_options', to='departments.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Opção do Menu',
                'verbose_name_plural': 'Opções do Menu',
                'db_table': 'bot_menu_option',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='botconfig',
            index=models.Index(fields=['is_active'], name='bot_config_is_acti_c8309e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='botmenuoption',
            unique_together={('bot_config', 'option_key')},
        ),
    ]
