# Generated by Django 5.0.14 on 2026-07-27 22:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('message.received', 'Mensagem recebida'), ('message.sent', 'Mensagem enviada'), ('conversation.started', 'Conversa iniciada'), ('conversation.assigned', 'Conversa atribuída'), ('conversation.transferred', 'Conversa transferida'), ('conversation.closed', 'Conversa encerrada'), ('attendant.online', 'Atendente online'), ('attendant.offline', 'Atendente offline'), ('client.blocked', 'Cliente bloqueado'), ('channel.disconnected', 'Canal desconectado'), ('integration.sync', 'Sincronização de integração'), ('system.alert', 'Alerta do sistema')], max_length=50, verbose_name='Tipo de evento')),
                ('data', models.JSONField(default=dict, verbose_name='Dados')),
                ('source', models.CharField(blank=True, default='', max_length=100, verbose_name='Origem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensagem de erro')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='events_event_t_c9f56c_idx'), models.Index(fields=['status'], name='events_status_8890b6_idx'), models.Index(fields=['created_at'], name='events_created_9e2206_idx'), models.Index(fields=['event_type', 'status'], name='events_event_t_e1f6e6_idx')],
            },
        ),
    ]
