# Generated by Django 5.0.14 on 2026-07-27 22:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('channel_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('facebook', 'Facebook Messenger'), ('instagram', 'Instagram'), ('webchat', 'Web Chat'), ('email', 'E-mail'), ('sms', 'SMS')], max_length=20, verbose_name='Tipo de canal')),
                ('provider', models.CharField(choices=[('evolution', 'Evolution API'), ('meta_cloud', 'Meta Cloud API'), ('twilio', 'Twilio'), ('gupshup', 'Gupshup')], default='evolution', max_length=20, verbose_name='Provedor')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Número de telefone')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configurações')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('connected', 'Conectado'), ('disconnected', 'Desconectado'), ('expired', 'Expirado'), ('error', 'Erro')], default='pending', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('webhook_url', models.URLField(blank=True, default='', verbose_name='Webhook URL')),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=255, verbose_name='Segredo do webhook')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canais',
                'db_table': 'channels',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('session_data', models.JSONField(blank=True, default=dict, verbose_name='Dados da sessão')),
                ('qr_code', models.TextField(blank=True, default='', verbose_name='QR Code')),
                ('qr_code_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiração do QR Code')),
                ('connection_status', models.CharField(choices=[('pending', 'Pendente'), ('connected', 'Conectado'), ('disconnected', 'Desconectado'), ('expired', 'Expirado'), ('error', 'Erro')], default='pending', max_length=20, verbose_name='Status da conexão')),
                ('last_connected_at', models.DateTimeField(blank=True, null=True, verbose_name='Última conexão')),
                ('webhook_config', models.JSONField(blank=True, default=dict, verbose_name='Configuração do webhook')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Tentativas')),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_session', to='channels_app.channel', verbose_name='Canal')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Sessão WhatsApp',
                'verbose_name_plural': 'Sessões WhatsApp',
                'db_table': 'channels_whatsapp_session',
            },
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['channel_type'], name='channels_channel_2bceca_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['provider'], name='channels_provide_21af6a_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['status'], name='channels_status_6fb705_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['company', 'is_active'], name='channels_company_f317f0_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappsession',
            index=models.Index(fields=['connection_status'], name='channels_wh_connect_6283fa_idx'),
        ),
    ]
