# Generated by Django 5.0.14 on 2026-07-27 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão'), ('login', 'Login'), ('logout', 'Logout'), ('transfer', 'Transferência'), ('assign', 'Atribuição'), ('close', 'Fechamento')], max_length=20)),
                ('resource_type', models.CharField(max_length=255)),
                ('resource_id', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'action'], name='observabili_company_a3fce5_idx'), models.Index(fields=['company', 'created_at'], name='observabili_company_63a525_idx')],
            },
        ),
    ]
