# Generated by Django 5.0.14 on 2026-07-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão'), ('login', 'Login'), ('logout', 'Logout'), ('transfer', 'Transferência'), ('assign', 'Atribuição'), ('close', 'Fechamento'), ('password_reset', 'Redefinição de Senha')], max_length=20),
        ),
    ]
