# Generated by Django 5.0.14 on 2026-07-27 22:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels_app', '0001_initial'),
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('max_wait_time', models.IntegerField(default=300, verbose_name='Tempo máx. espera (s)')),
                ('max_concurrent', models.IntegerField(default=10, verbose_name='Máx. simultâneos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='Empresa')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='departments.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Fila',
                'verbose_name_plural': 'Filas',
                'db_table': 'conversations_queue',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('waiting', 'Aguardando'), ('active', 'Em atendimento'), ('transferred', 'Transferida'), ('closed', 'Encerrada')], default='waiting', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('is_bot_active', models.BooleanField(default=True, verbose_name='Bot ativo')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Última mensagem')),
                ('last_message_preview', models.TextField(blank=True, default='', verbose_name='Pré-visualização')),
                ('message_count', models.IntegerField(default=0, verbose_name='Total de mensagens')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Encerrada em')),
                ('attendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Atendente')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='channels_app.channel', verbose_name='Canal')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='clients.client', verbose_name='Cliente')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Encerrada por')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='Empresa')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='departments.department', verbose_name='Departamento')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='conversations.queue', verbose_name='Fila')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'db_table': 'conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('shortcut', models.CharField(max_length=50, verbose_name='Atalho')),
                ('is_shared', models.BooleanField(default=False, verbose_name='Compartilhado')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='Categoria')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='Empresa')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_responses', to='departments.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Resposta Rápida',
                'verbose_name_plural': 'Respostas Rápidas',
                'db_table': 'conversations_quick_response',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Motivo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceita'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada')], default='pending', max_length=10, verbose_name='Status')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvida em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='Empresa')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='conversations.conversation', verbose_name='Conversa')),
                ('from_attendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to=settings.AUTH_USER_MODEL, verbose_name='Atendente de origem')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='departments.department', verbose_name='Departamento de origem')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('to_attendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to=settings.AUTH_USER_MODEL, verbose_name='Atendente de destino')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='departments.department', verbose_name='Departamento de destino')),
            ],
            options={
                'verbose_name': 'Transferência',
                'verbose_name_plural': 'Transferências',
                'db_table': 'conversations_transfer',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('sender_type', models.CharField(choices=[('client', 'Cliente'), ('attendant', 'Atendente'), ('bot', 'Bot'), ('system', 'Sistema')], max_length=10, verbose_name='Tipo de remetente')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('document', 'Documento'), ('location', 'Localização'), ('button', 'Botão'), ('list', 'Lista'), ('template', 'Template'), ('system', 'Sistema')], default='text', max_length=10, verbose_name='Tipo de mensagem')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('media_url', models.URLField(blank=True, default='', verbose_name='URL da mídia')),
                ('media_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome da mídia')),
                ('media_size', models.IntegerField(blank=True, null=True, verbose_name='Tamanho da mídia (bytes)')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou')], default='sent', max_length=10, verbose_name='Status de entrega')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('external_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID externo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='Empresa')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation', verbose_name='Conversa')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='conversations.message', verbose_name='Resposta a')),
                ('sender_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='clients.client', verbose_name='Remetente (cliente)')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remetente (usuário)')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'db_table': 'conversations_message',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sender_type'], name='conversatio_sender__983bac_idx'), models.Index(fields=['message_type'], name='conversatio_message_792495_idx'), models.Index(fields=['delivery_status'], name='conversatio_deliver_0b7845_idx'), models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_4b968d_idx'), models.Index(fields=['created_at'], name='conversatio_created_792fff_idx'), models.Index(fields=['external_id'], name='conversatio_externa_07bfa9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('role', models.CharField(choices=[('attendant', 'Atendente'), ('supervisor', 'Supervisor'), ('observer', 'Observador')], default='attendant', max_length=20, verbose_name='Função na conversa')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Entrou em')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Saiu em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='Empresa')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='conversations.conversation', verbose_name='Conversa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'db_table': 'conversations_participant',
                'indexes': [models.Index(fields=['is_active'], name='conversatio_is_acti_db1815_idx')],
                'unique_together': {('conversation', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['is_active'], name='conversatio_is_acti_9c8dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['department', 'is_active'], name='conversatio_departm_c0af1b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status'], name='conversatio_status_742c74_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['priority'], name='conversatio_priorit_847c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='conversatio_last_me_594294_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['attendant', 'status'], name='conversatio_attenda_b608ce_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['company', 'status'], name='conversatio_company_d9a5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['client', 'status'], name='conversatio_client__a44c50_idx'),
        ),
        migrations.AddIndex(
            model_name='quickresponse',
            index=models.Index(fields=['shortcut'], name='conversatio_shortcu_637062_idx'),
        ),
        migrations.AddIndex(
            model_name='quickresponse',
            index=models.Index(fields=['category'], name='conversatio_categor_6b22cb_idx'),
        ),
        migrations.AddIndex(
            model_name='quickresponse',
            index=models.Index(fields=['is_shared'], name='conversatio_is_shar_e2e27f_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status'], name='conversatio_status_836103_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['conversation', 'status'], name='conversatio_convers_3b3716_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['to_attendant', 'status'], name='conversatio_to_atte_bdb320_idx'),
        ),
    ]
