# Generated by Django 5.0.14 on 2026-07-27 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nome do arquivo')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo MIME')),
                ('file_url', models.URLField(blank=True, default='', verbose_name='URL do arquivo')),
                ('file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Caminho do arquivo')),
                ('media_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('document', 'Documento'), ('location', 'Localização'), ('button', 'Botão'), ('list', 'Lista'), ('template', 'Template'), ('system', 'Sistema')], default='document', max_length=20, verbose_name='Tipo de mídia')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Largura')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Altura')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duração (s)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='Empresa')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='conversations.conversation', verbose_name='Conversa')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='conversations.message', verbose_name='Mensagem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'db_table': 'conversations_attachment',
                'indexes': [models.Index(fields=['media_type'], name='conversatio_media_t_0cd1ea_idx'), models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_7ae20f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('event_type', models.CharField(max_length=50, verbose_name='Tipo de evento')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='Empresa')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='conversations.conversation', verbose_name='Conversa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_entries', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Linha do Tempo',
                'verbose_name_plural': 'Linhas do Tempo',
                'db_table': 'conversations_timeline',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_6d392a_idx'), models.Index(fields=['event_type'], name='conversatio_event_t_da047b_idx')],
            },
        ),
    ]
