# Generated by Django 5.0.14 on 2026-07-27 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='attendants', to='departments.department', verbose_name='Departamentos'),
        ),
        migrations.AddField(
            model_name='attendant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['company', 'role'], name='accounts_us_company_8958d5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_online'], name='accounts_us_is_onli_a6442c_idx'),
        ),
    ]
