# Generated by Django 5.0.14 on 2026-07-27 22:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('profile_picture', models.URLField(blank=True, default='', verbose_name='Foto de perfil')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('last_contact_at', models.DateTimeField(blank=True, null=True, verbose_name='Último contato')),
                ('total_conversations', models.IntegerField(default=0, verbose_name='Total de conversas')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='Empresa')),
                ('tags', models.ManyToManyField(blank=True, related_name='clients', to='tags.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clients',
                'indexes': [models.Index(fields=['phone'], name='clients_phone_459745_idx'), models.Index(fields=['email'], name='clients_email_4c8bec_idx'), models.Index(fields=['is_blocked'], name='clients_is_bloc_250bce_idx'), models.Index(fields=['last_contact_at'], name='clients_last_co_f579b8_idx'), models.Index(fields=['company', 'phone'], name='clients_company_904c6d_idx')],
                'unique_together': {('company', 'phone')},
            },
        ),
    ]
