# Generated by Django 5.0.14 on 2026-07-27 22:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('provider', models.CharField(choices=[('evolution', 'Evolution API'), ('meta_cloud', 'Meta Cloud API'), ('twilio', 'Twilio'), ('gupshup', 'Gupshup')], max_length=20, verbose_name='Provedor')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configurações')),
                ('credentials', models.JSONField(blank=True, default=dict, verbose_name='Credenciais')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('error', 'Erro')], default='inactive', max_length=10, verbose_name='Status')),
                ('webhook_url', models.URLField(blank=True, default='', verbose_name='URL do webhook')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização')),
                ('error_log', models.TextField(blank=True, default='', verbose_name='Log de erros')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Integração',
                'verbose_name_plural': 'Integrações',
                'db_table': 'integrations',
                'indexes': [models.Index(fields=['provider'], name='integration_provide_7ac907_idx'), models.Index(fields=['status'], name='integration_status_7ea6a9_idx'), models.Index(fields=['company', 'is_active'], name='integration_company_d499fc_idx')],
            },
        ),
    ]
